[template]
src = "production.tmpl"
dest = "./config/default.json"
keys = [
    "/configuration/discrete/worker/update/delay/seconds",
    "/configuration/discrete/worker/queue/task/type",
    "/configuration/discrete/worker/queue/job/type",
    "/configuration/discrete/worker/queue/job/manager/url",
    "/configuration/discrete/worker/queue/heartbeat/manager/url",
    "/configuration/discrete/worker/queue/heartbeat/interval/ms",
    "/configuration/discrete/worker/queue/dequeue/interval/ms",
	"/configuration/discrete/worker/kafka/host/ip",
    "/configuration/discrete/worker/kafka/topic",
    "/configuration/discrete/worker/kafka/group/id",
    "/configuration/discrete/worker/kafka/offest/reset",
    "/configuration/discrete/worker/kafka/poll/timeout/milliseconds",
    "/configuration/discrete/worker/kafka/poll/records",
    "/configuration/discrete/worker/kafka/ssl/context",
    "/configuration/discrete/worker/kafka/ssl/cafile",
    "/configuration/discrete/worker/kafka/ssl/certfile",
    "/configuration/discrete/worker/kafka/ssl/keyfile",
    "/configuration/discrete/worker/kafka/ssl/password",
    "/configuration/discrete/worker/logger/type",
    "/configuration/discrete/worker/logger/level",
    "/configuration/discrete/worker/logger/path",
    "/configuration/discrete/worker/logger/output",
    "/configuration/discrete/worker/discrete/storage/url",
    "/configuration/discrete/worker/overseer/url",
    "/configuration/discrete/worker/gdal/process/count",
    "/configuration/discrete/worker/gdal/resampling",
    "/configuration/discrete/worker/gdal/tms/compatible",
    "/configuration/discrete/worker/gdal/profile",
    "/configuration/discrete/worker/gdal/vrt/no/data",
    "/configuration/discrete/worker/gdal/vrt/output/srs",
    "/configuration/discrete/worker/gdal/vrt/resample/algo",
    "/configuration/discrete/worker/source/mount",
    "/configuration/discrete/worker/fs/external/physical/path",
    "/configuration/discrete/worker/fs/internal/outputs/path",
    "/configuration/discrete/worker/s3/endpoint/url",
    "/configuration/discrete/worker/s3/access/key/id",
    "/configuration/discrete/worker/s3/secret/access/key",
    "/configuration/discrete/worker/s3/bucket",
    "/configuration/discrete/worker/s3/ssl/enabled",
    "/configuration/discrete/worker/s3/virtual/hosting",
    "/configuration/discrete/worker/storage/provider",
    "/configuration/discrete/worker/max/attempts",
]
