[template]
src = "production.tmpl"
dest = "./config/default.json"
keys = [
	"/configuration/discrete/worker/kafka/host/ip",
    "/configuration/discrete/worker/kafka/topic",
    "/configuration/discrete/worker/kafka/group/id",
    "/configuration/discrete/worker/kafka/offest/reset",
    "/configuration/discrete/worker/kafka/poll/timeout/milliseconds",
    "/configuration/discrete/worker/kafka/poll/records",
    "/configuration/discrete/worker/logger/type",
    "/configuration/discrete/worker/logger/level",
    "/configuration/discrete/worker/logger/path",
    "/configuration/discrete/worker/logger/output",
    "/configuration/discrete/worker/discrete/storage/url",
    "/configuration/discrete/worker/gdal/multithread",
    "/configuration/discrete/worker/gdal/thread/count",
    "/configuration/discrete/worker/gdal/vrt/folder",
    "/configuration/discrete/worker/gdal/vrt/no/data",
    "/configuration/discrete/worker/gdal/vrt/output/srs",
    "/configuration/discrete/worker/gdal/vrt/resample/algo",
    "/configuration/discrete/worker/fs/external/physical/path",
    "/configuration/discrete/worker/fs/internal/outputs/path",
    "/configuration/discrete/worker/s3/endpoint/url",
    "/configuration/discrete/worker/s3/access/key/id",
    "/configuration/discrete/worker/s3/secret/access/key",
    "/configuration/discrete/worker/s3/bucket",
    "/configuration/discrete/worker/s3/download/expired/time",
    "/configuration/discrete/worker/s3/ssl/enabled",
    "/configuration/discrete/worker/s3/virtual/hosting",
    "/configuration/discrete/worker/storage/provider",
    "/configuration/discrete/worker/max/attempts",
]
